package com.tuvarna.oop2project.models;

import java.util.List;

public class Hotel {
    //the id will be generated by the database
    private long id;
    private String name;
    private int floors;
    private int roomsPerFloor;
    private List<Room> rooms;
    private User owner;
    private User manager;

    public Hotel(String name, int floors, int roomsPerFloor, List<Room> rooms, User owner, User manager) {
        this.name = name;
        this.floors = floors;
        this.roomsPerFloor = roomsPerFloor;
        this.rooms = rooms;
        this.owner = owner;
        this.manager = manager;
    }

    public int getFloors() {
        return floors;
    }

    public void setFloors(int floors) {
        this.floors = floors;
    }

    public int getRoomsPerFloor() {
        return roomsPerFloor;
    }

    public void setRoomsPerFloor(int roomsPerFloor) {
        this.roomsPerFloor = roomsPerFloor;
    }

    public List<Room> getRooms() {
        return rooms;
    }

    public void setRooms(List<Room> rooms) {
        this.rooms = rooms;
    }

    public User getOwner() {
        return owner;
    }

    public void setOwner(User owner) {
        this.owner = owner;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public User getManager() {
        return manager;
    }

    public void setManager(User manager) {
        this.manager = manager;
    }
}
